[mypy]
exclude = rag-poc/
ignore_missing_imports = True
disallow_untyped_defs = False
follow_untyped_imports = True

[mypy-yaml]
ignore_missing_imports = True

[mypy-requests]
ignore_missing_imports = True
